stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - npm install -g pm2 # Menggunakan PM2 untuk menjalankan aplikasi di production (bisa diganti jika tidak menggunakan pm2)
    - pm2 start index.js
